lista = [1,2,3,4,5,6,7,8,9]
print(lista)
lista.append(10)
lista.append(5)
lista.append(3)
lista.append(9)
print("Se muestran los elementos de la lista")
print(lista)
print("Se muestra el primer elemento de la lista")
print(lista[0])
lista2 = lista.copy()
print("Se muestra una copia de la lista principal")
print(lista2)
lista.clear()
print("se muestra la lista princpal vacia con clear")
print("Se muestra la copia de la lista principal")
print(lista2)
print("Se muestra cuantas veces aparece el elemento 5 de la lista")
print(lista2.count(5))
print("Se muestra cuantos elementos tiene la lista")
print(len(lista2))
print("Se elimina el 5to elemento de la lista 2")
lista2.pop(4)
print(lista2)
print("Se elimina el ultimo 5 de la lista 2")
lista2.remove(5)
print(lista2)
print("Se imprime la lista en orden inverso al que se fue agregando los items")
lista2.reverse()
print(lista2)
print("Se imprime la lista ordenada")
lista2.sort()
print(lista2)
print("Se imprime la lista en orden inverso")
lista2.reverse()
print(lista2)

